/** Repository files copied verbatim into the public static artifact. */
export const PUBLIC_SOURCE_FILES = Object.freeze([
  '.nojekyll',
  '404.html',
  'AGENTS.md',
  'LICENSE',
  'index.html',
  'learning.html',
  'manifest.webmanifest',
  'offline.html',
  'robots.txt',
  'sitemap.xml',
  'sw.js',
]);

/** Repository directories copied recursively into the public static artifact. */
export const PUBLIC_SOURCE_DIRECTORIES = Object.freeze([
  'assets',
  'curation',
  'docs',
  'evaluation',
  'graph',
  'integrations',
  'prompts',
  'src',
]);

/** Files generated by the build after source inputs are copied. */
export const GENERATED_PUBLIC_FILES = Object.freeze([
  '_headers',
  'build-manifest.json',
]);

export const PUBLIC_BUILD_INPUTS = Object.freeze([
  ...PUBLIC_SOURCE_FILES,
  ...PUBLIC_SOURCE_DIRECTORIES,
]);

const GRAPH_INDEX_PATH_MAPS = Object.freeze([
  'canonical_files',
  'schemas',
  'generated_files',
  'integrations',
]);

const topLevelFiles = new Set([...PUBLIC_SOURCE_FILES, ...GENERATED_PUBLIC_FILES]);
const topLevelDirectories = new Set(PUBLIC_SOURCE_DIRECTORIES);

/** Return true only for a repository-relative path in the deployed public surface. */
export function isPublicArtifactPath(value) {
  if (typeof value !== 'string') return false;
  const relativePath = value.replace(/^\/+|\/+$/gu, '');
  if (!relativePath || relativePath.includes('\\') || relativePath.includes('\0')) return false;
  const segments = relativePath.split('/');
  if (segments.some((segment) => !segment || segment === '.' || segment === '..')) return false;
  if (relativePath === '.nojekyll') return true;
  if (segments.some((segment) => segment.startsWith('.'))) return false;
  if (segments.length === 1) return topLevelFiles.has(relativePath);
  return topLevelDirectories.has(segments[0]);
}

/** Return every repository path advertised by graph/index.json. */
export function collectGraphIndexArtifactPaths(index) {
  const paths = GRAPH_INDEX_PATH_MAPS.flatMap((field) => Object.values(index[field]));
  paths.push(...index.agent_entrypoints);
  return [...new Set(paths)].sort();
}

/** Require graph/index.json discovery metadata to describe a closed public artifact. */
export function assertGraphIndexArtifactClosure(index, artifactPaths) {
  for (const path of collectGraphIndexArtifactPaths(index)) {
    if (!isPublicArtifactPath(path)) throw new Error(`Graph index path is outside the public surface: ${path}`);
    if (!artifactPaths.has(path)) throw new Error(`Graph index path is missing from the public artifact: ${path}`);
  }
}
