import { fileURLToPath } from 'node:url';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = fileURLToPath(new URL('..', import.meta.url));
const check = process.argv.includes('--check');
const read = (path) => JSON.parse(readFileSync(join(root, path), 'utf8'));
const nodes = read('graph/nodes/core.json');
const edges = read('graph/edges.json');
const collections = read('graph/collections.json');
const byId = new Map(nodes.map((node) => [node.id, node]));
const out = new Map();

const counts = (values, key) => Object.entries(values.reduce((acc, item) => {
  acc[item[key]] = (acc[item[key]] ?? 0) + 1;
  return acc;
}, {})).sort(([a], [b]) => a.localeCompare(b));

out.set('views/generated-index.md', `# Generated graph index\n\n> Generated by \`npm run generate:views\`. Do not edit manually.\n\n- Nodes: **${nodes.length}**\n- Edges: **${edges.length}**\n- Collections: **${collections.length}**\n\n## Nodes by kind\n\n${counts(nodes, 'kind').map(([kind, count]) => `- ${kind}: ${count}`).join('\n')}\n\n## Nodes by confidence\n\n${counts(nodes, 'confidence').map(([confidence, count]) => `- ${confidence}: ${count}`).join('\n')}\n\n## Relations\n\n${counts(edges, 'relation').map(([relation, count]) => `- ${relation}: ${count}`).join('\n')}\n`);

const roots = nodes.filter((node) => !edges.some((edge) => edge.target === node.id));
const children = new Map(nodes.map((node) => [node.id, []]));
for (const edge of edges.filter((item) => ['uses', 'depends_on', 'generalizes', 'bridge'].includes(item.relation))) {
  children.get(edge.source)?.push(edge.target);
}
for (const list of children.values()) list.sort((a, b) => byId.get(a).title.localeCompare(byId.get(b).title));
const treeLines = ['# Structural tree view', '', '> This is a lossy projection of the graph. Cross-links and evidence labels remain canonical in `graph/edges.json`.', ''];
const shown = new Set();
function walk(id, depth) {
  const node = byId.get(id);
  if (!node || shown.has(id) || depth > 4) return;
  shown.add(id);
  treeLines.push(`${'  '.repeat(depth)}- **${node.title}** \`${node.id}\``);
  for (const child of children.get(id) ?? []) walk(child, depth + 1);
}
for (const node of roots.sort((a, b) => a.title.localeCompare(b.title))) walk(node.id, 0);
const remaining = nodes.filter((node) => !shown.has(node.id)).sort((a, b) => a.title.localeCompare(b.title));
if (remaining.length) {
  treeLines.push('', '## Cross-linked or cyclic-projection nodes', '');
  for (const node of remaining) treeLines.push(`- **${node.title}** \`${node.id}\``);
}
out.set('views/tree.md', `${treeLines.join('\n')}\n`);

const millennium = collections.find((collection) => collection.id === 'collection.millennium');
const millLines = ['# Millennium problem map', '', '| Problem | Status | Direct inputs | Lean target |', '| --- | --- | --- | --- |'];
for (const id of millennium.nodes) {
  const node = byId.get(id);
  const inputs = edges.filter((edge) => edge.target === id).map((edge) => byId.get(edge.source)?.title).filter(Boolean).join(', ');
  millLines.push(`| ${node.title} | ${node.status} | ${inputs || '—'} | ${node.lean.targets[0] ?? '—'} |`);
}
out.set('views/millennium-map.md', `${millLines.join('\n')}\n`);

const domains = nodes.filter((node) => node.kind === 'domain').sort((a, b) => a.title.localeCompare(b.title));
const matrixLines = ['# Domain matrix', '', '| Domain | Confidence | Tags | Degree |', '| --- | --- | --- | ---: |'];
for (const node of domains) {
  const degree = edges.filter((edge) => edge.source === node.id || edge.target === node.id).length;
  matrixLines.push(`| ${node.title} | ${node.confidence} | ${node.tags.join(', ')} | ${degree} |`);
}
out.set('views/domain-matrix.md', `${matrixLines.join('\n')}\n`);

const mermaid = ['flowchart LR'];
const safe = (id) => id.replaceAll('.', '_');
for (const node of nodes) mermaid.push(`  ${safe(node.id)}["${node.title.replaceAll('"', "'")}"]`);
for (const edge of edges) mermaid.push(`  ${safe(edge.source)} -->|${edge.relation}| ${safe(edge.target)}`);
out.set('views/knowledge-graph.mmd', `${mermaid.join('\n')}\n`);

let stale = false;
for (const [path, content] of out) {
  const absolute = join(root, path);
  if (check) {
    let existing = '';
    try { existing = readFileSync(absolute, 'utf8'); } catch { /* missing is stale */ }
    if (existing !== content) {
      console.error(`Stale generated view: ${path}`);
      stale = true;
    }
  } else {
    writeFileSync(absolute, content);
    console.log(`Wrote ${path}`);
  }
}
if (stale) process.exitCode = 1;
else if (check) console.log(`Validated ${out.size} generated views.`);
